import { defineConfig } from "oxfmt";

export default defineConfig({
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  bracketSameLine: false,
  trailingComma: "all",

  sortImports: true,
  sortPackageJson: true,

  sortTailwindcss: {
    stylesheet: "./src/index.css",
    functions: ["cn", "clsx", "cva"],
  },

  ignorePatterns: [
    "node_modules",
    "dist",
    ".github",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "pnpm-debug.log*",
    ".env",
    ".env.*.local",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    ".git",
    ".idea",
    ".DS_Store",
    "Thumbs.db",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.icns",
    "*.svg",
    "*.pdf",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.wasm",
    "README.md",
  ],
});
